name: magic_deeplink
description: Deep linking support for Magic Framework (Universal Links, App Links).
version: 0.0.1-alpha.1
homepage: https://magic.fluttersdk.com/deeplink
documentation: https://magic.fluttersdk.com/packages/deeplink/getting-started/installation
repository: https://github.com/fluttersdk/magic_deeplink
issue_tracker: https://github.com/fluttersdk/magic_deeplink/issues

topics:
  - deeplink
  - universal-links
  - app-links
  - magic
  - flutter

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  magic: ^1.0.0-alpha.3
  magic_cli: ^0.0.1-alpha.3
  app_links: ^7.0.0
  args: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.0
  flutter_lints: ^6.0.0

executables:
  magic_deeplink: magic_deeplink
